### ISSUE TITLE
Motivation

### ISSUE THREAD

**Issue by meabed** [me-io/community#1]
# Motivation

> Foster the tech in Middle East, North Africa, Central Africa and Southern/Western Asia. 

The Middle East, North Africa, Central Africa and Western Asia is the home of many software engineers, developers, students and tech people of all genders.

## There is a huge gap

- Tech evangelism, developer advocacy and developer relations
- OSS collaboration and contribution
- Female participation in the tech and community involvement 
- Students networking and path to relevant market technology
- Early participation of students in open source and tech community
- Developers talent development, mentoring, advisory
- Entry to local and global software job market
- Developer events, that are useful, relevant and consistent
- Relevant and Quality tech jobs and sponsors
- Global collaboration and networking with developers and communities
- Kids computer and code education

# Introducing me.io

> A Developer first and open-source community by developers

We are bunch of self-motivated, ambitious developers living and working in the region, aiming to fill this gap by building and actively participating in the community and pushing the wheel of progress forward.

Building and growing the community is not an easy or an individual task, and we looking to join efforts with everyone, so if you are reading this and think you could help, please do reach out to us and we would be happy to get you started.
Come and hangout with us
   
# Bridging the gap
- Open-source contribution
- Developer events organization
- Advisory and mentoring
- Networking

# OSS Contributors
> We need your help, please reach out if you would like to help

We would love for everyone to get involved, get your hands dirty and let us build software together.  
 
# Final words
Over the past few years, many of us are putting efforts to build and grow the tech scene and the community in the region, these initiatives is great, and we aim to complement and contribute inclusively with everyone and join efforts in improving the tech in region.

# Reach out and Connect
Find us on:
- [Twitter](https://me.io/twitter)
- [Telegram `because privacy matters`](https://me.io/join-telegram)
- [Whatsapp](https://me.io/join-whatsapp)
- [Slack](https://me.io/join-slack)
- [Meetup](https://me.io/meetup-group)
> All communications are welcomed wholeheartedly, Say HI, Support, Suggest, Contribute, Share, Connect.

**Comment by Zaiklon** [comment]
Awesome, Your most important job is to build a heathy workplace, create more jobs, inspire and aspire in the process. And leave the world a better place than you found it.

**Comment by Zaiklon** [comment]
-
The most important job is to build a heathy workplace, create more jobs, inspire and aspire in the process. And leave the world a better place than you found it.
✌"All My Best Wishes" ✌
