### ISSUE TITLE
Group Introduction

### ISSUE THREAD

**Issue by meabed** [me-io/community#2]
# Motivation
Read our [motivation page](https://me.io/motivation)

# Intro
ME.IO is a technology and developer focused group. We aim to  contribute in building the developer community in the Middle East through organizing and participation of events in Dubai #DXB, Riyadh #RUH and Cairo #CAI, with other cities in the future.

We aim to:
- Foster a Developer Centric community
- Build a group that  engage, help, share, connect, incubate and represent developers in the region
- Amplify useful and practical learning, things that could be applied in professional or personal work, or new projects
- Improve Women participation in tech
- Raise open source awareness, participation and contribution
- Improve the tech culture with topics such as:
	- Teamwork and collaboration
	- Openness and Transparency
	- Diversity
	- Communication 
	- Work/Life Balance
	- Feedback and Self improvement
	- Continuous development and Career growth
- Connect developers with jobs and business opportunities
- Nurture and shape skills, talents and abilities that improve the tech community and contribute to everyone success

# Activities
Monthly Meetup with topics such as:
- PHP 
	- Topics such as: Symfony, Laravel, Wordpress, CMS, PHP 7.{1,2,3},...
- Golang
	- Topics such as: learning golang, building API's, cli applications, ...
- Javascript
	- Topics such as: node.js, reactjs, angularjs, nextjs,...
- DevTools and Productivity
	- Topics such as: IDE, Developer Machine, Productivity hacks, Tips and Tricks, Time-management,...
- QA:
	- Topics such as: Appium, Selenium, Testing Management, Testing Automation,...

Open topics TBD:
- Java
- .NET
- Devops Meetup

Newsletter:
- Weekly
- [Generated and Maintained by the community](https://me.io/newsletter-repo)
- Subscribe now - No spam :) - only good stuff!

> Activities are organized based on the community demand and the speakers availability. We will try as much as we can to organize continuous meetups. Feel free to reach out if you have suggestions, or you want to participate or speak.

# Contribution 
We will not be a community without a community. And We are not looking for The One, we are looking for Everyone.
So if you are here reading this and you could make this place better than you found it, reach out, join the group, participate, be a speaker or an organizer or a sponsor, share knowledge, experience, and ideas, give suggestions and feedback and let's meet up.

### 1120 bit about me.
This is Meabed, Yet another "human" in tech, you could learn more about me @ https://twitter.com/meabed, https://www.linkedin.com/in/mmeabed

# Reach out and Connect
Find us on:
- [Twitter](https://me.io/twitter)
- [Telegram `because privacy matters`](https://me.io/join-telegram)
- [Whatsapp](https://me.io/join-whatsapp)
- [Slack](https://me.io/join-slack)
- [Meetup](https://me.io/meetup-group)
> All communications are welcomed wholeheartedly, Say HI, Support, Suggest, Contribute, Share, Connect.

**Comment by Zaiklon** [comment]
**Wishing you all the best of luck ✌**

**Comment by Zaiklon** [comment]
-
Wishing you all the best of luck ✌
