### ISSUE TITLE
Speakers

### ISSUE THREAD

**Issue by meabed** [me-io/community#4]
# Speak at an event

Whether you are an aspiring speaker who wants to speak or a veteran with an interesting idea, reach out to us and speak at one of the upcoming meetups.

Please make sure to reach out to us even if you are short of ideas to speak about - we can come up with something for you.

### [Contact us](mailto:community@me.io?subject=%5BSpeaker%5D+Hello+there!&body=Dear+Community%2C+My+name+is)

**Comment by Usamaliaquat123** [comment]
sure 👍

**Comment by majidmvulle** [comment]
@meabed I'm interested to speak on the next event

**Comment by meabed** [comment]
> @meabed I'm interested to speak on the next event
Awesome!
Could you please send an email [here](mailto:community@me.io?subject=%5BSpeaker%5D+Hello+there!&body=Dear+Community%2C+My+name+is)

Thanks
