### ISSUE TITLE
01. ME.IO DXB Meetup - Date: 20 Dec 2018

### ISSUE THREAD

**Issue by meabed** [me-io/community#5]
# Thank you for attending the meetup 

<h3 align='center'><a href="https://me.io/meetup-1/files">Download the meetup presentations
<img src="https://i.ibb.co/FXkjKmD/meetup-1-files.png"/>
<img src="https://i.ibb.co/stdqNX8/meeup-01-images.png"/>
</a></h3>
<h2 align='center'><a href="https://me.io/meetup-1/feedback">Fill the feedback form and help us improve the next meetups.<a/></h2>

<h1 align='center'>Meetup Summary</h1>

# 01. ME.IO Dev Group Intro && Tech talks
> Meet and greet and kicking things off

## Meetup datetime [RSVP here ](https://www.meetup.com/ME-IO-DXB/events/257096479/)
- **Date**: Thursday, 20 Dec 2018
- **Time**: Starts at 7.00 PM
- **Location**: Amazon Web Services "AWS" office, Dubai Properties Group Building, Al Falak Street / 17, Al Bourooj Street, Dubai Internet City - [Google Map](https://maps.app.goo.gl/Zcxvg) - [Find Location Map Below](#locationmap)

> [Suggest a host or sponsor for future meetups](mailto:community@me.io?subject=%5BSponsor%5D+Hello+there!&body=Dear+Community%2C+My+name+is)

## Meetup talks
> Topics focus: Full Stack Web Development

- 7.00 to 7.15 - Group introduction - [Mohamed Meabed](https://twitter.com/meabed) @meabed 
- 7.15 to 7.45 - Crafting Good APIs - [Kamran Ahmed](https://twitter.com/kamranahmedse) @kamranahmedse 
- 7.45 to 8.15 - Containers from bottom up - [Muslim AbuTaha](https://github.com/abutaha) @abutaha
- 8.15 to 8.45 - Micro-frontend Architecture - [Khurrum Qureshi](https://twitter.com/KhurrumQureshi1) @khurrumqureshi 
- 8.45 to 9.30 - Pizza and Networking

<img  src="https://i.ibb.co/kXP1fcM/meetup-1-speakers.jpg">

---

### Feedback and suggestions
- Would you want to suggest a topic, speaker, organizer or sponsor.
- Do you have an idea or suggestion that you would like to see it in the group
 - Or if you have any general feedback, we want to listen.
Please share your feedback and suggestions [here](https://github.com/me-io/feedback/issues)

---

## Spread the word
> Help us build and grow the best tech community 🙌

Invite developers and techies and surround your self with people you love to be with, make like-minded friends and expand your developer network!

### A note to our sponsor [AWS](https://aws.amazon.com/aws-me/)

<a href="https://aws.amazon.com/aws-me/">
<img align="left" height="70" width="206" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/AmazonWebservices_Logo.svg/2000px-AmazonWebservices_Logo.svg.png">
</a>
Many thanks to Amazon Web Services (AWS) for stepping up as our first sponsor for this group by providing the venue and the food.

&nbsp;
&nbsp;
> If you are interested in sponsorship for the ME.IO Dev Group Meeups, please drop us a line [here](mailto:community@me.io?subject=%5BSponsor%5D+Hello+there!&body=Dear+Community%2C+My+name+is)

---
## Location map
![map](https://i.ibb.co/NNwx5cn/25-06-14-1-N-55-10-05-7-E-Google-Maps.jpg)

---
## Thank you

Thank you everyone for joining the me.io dev groups and for your contributions in building a developer community in the region.

Dubai is one of those few places that is equipped with infrastructure, security and entertainment and with our community building efforts, we should be able to foster and nurture an always growing world-class tech community.

## More about us

- [ ] Read the [motivation](https://me.io/motivation) behind me.io and learn more about [the group](https://me.io/group-intro)
- [ ] Subscribe to [the newsletter](https://me.io/subscribe-to-our-newsletter)
- [ ] Socialize and follow us on[Twitter](https://me.io/twitter)

---

**Comment by meabed** [comment]
Date: 12 December 2018
Location: TBA

**Comment by meabed** [comment]
Date: Monday 10 December 2018
Location: TBA

**Comment by meabed** [comment]
Date: Tuesday 20 December 2018
Location: TBA

**Comment by meabed** [comment]
Date: Tuesday 10 January 2019
Location: TBA

**Comment by Zaiklon** [comment]
Vote 👍✌👍

**Comment by Zaiklon** [comment]
Vote ✌

**Comment by sbatliwala** [comment]
Vote

**Comment by khurrumqureshi** [comment]
I would like to suggest a topic for meetup "**Micro-frontend Architecture**"

**Comment by ayazisdeveloper** [comment]
I would like to suggest **11 December 2018 - It's Tuesday**. Also I can see wrong date and day in above comments because there is **Wednesday 10 December 2018** in my calendar, it's **Monday** actually.

**Comment by msaadsaif5** [comment]
How about 13th December after 18:30? Its weekend and we can hang around for more time :100:

**Comment by meabed** [comment]
> How about 13th December after 18:30? Its weekend and we can hang around for more time 💯

I think many people have some commitments in weekends :) workdays are easier to accommodate with everyone :)

**Comment by msaadsaif5** [comment]
> > How about 13th December after 18:30? Its weekend and we can hang around for more time 💯
> 
> I think many people have some commitments in weekends :) workdays are easier to accommodate with everyone :)

Sure, I'd be able to join between 12th and 17th due to some traveling going on. I hope we get more votes in these dates.

**Comment by meabed** [comment]
> > > How about 13th December after 18:30? Its weekend and we can hang around for more time 💯
> > 
> > 
> > I think many people have some commitments in weekends :) workdays are easier to accommodate with everyone :)
> 
> Sure, I'd be able to join between 12th and 17th due to some traveling going on. I hope we get more votes in these dates.

Great, could you vote that options up 👍  :)

**Comment by ehsansajjad465** [comment]
What's the location in DXB for this ?

**Comment by meabed** [comment]
> What's the location in DXB for this ?

We have proposed dates up in the issue thread, have a look :) most likely it will be 20-Dec-2018
Thanks for asking :)

**Comment by abutaha** [comment]
Hi guys.

I would like to invite you to our office (Amazon Web Services "AWS" office). I've booked a room on 20 Dec from 7:00pm to 9:30pm. There will be parking slots and some food as well.

Please join us there.
https://goo.gl/maps/v8UAZvkHYoS2

@meabed would you please update meetup with date/time/location.

Thanks,

**Comment by ehsansajjad465** [comment]
> Hi guys.
> 
> I would like to invite you to our office (Amazon Web Services "AWS" office). I've booked a room on 20 Dec from 7:00pm to 9:30pm. There will be parking slots and some food as well.
> 
> Please join us there.
> https://goo.gl/maps/v8UAZvkHYoS2
> 
> @meabed would you please update meetup with date/time/location.
> 
> Thanks,

It would be great if we could have these events on weekend days. It's difficult in week days to reach due to work commitments.

**Comment by meabed** [comment]
> > Hi guys.
> > I would like to invite you to our office (Amazon Web Services "AWS" office). I've booked a room on 20 Dec from 7:00pm to 9:30pm. There will be parking slots and some food as well.
> > Please join us there.
> > https://goo.gl/maps/v8UAZvkHYoS2
> > @meabed would you please update meetup with date/time/location.
> > Thanks,
> 
> It would be great if we could have these events on weekend days. It's difficult in week days to reach due to work commitments.

Thanks @ehsansajjad465 
We will try in the future meetups and see if we could get a meetup on weekends.

**Comment by ayazisdeveloper** [comment]
Any one can come there to attend this event?

**Comment by meabed** [comment]
@ayazisdeveloper Yes :) everyone is welcome

**Comment by mabdelfattah** [comment]
@meabed RSVP link is not working.

**Comment by meabed** [comment]
> @meabed RSVP link is not working.
> @meabed RSVP link is broken.

@adeelshah @mabdelfattah fixed. :) Thanks
